jdbc:
  url: "jdbc:postgresql://localhost:5432/test"
  user: "postgres"
  password: "Lina18061988"



spring:
  datasource:
    username: "postgres"
    password: "Lina18061988"
    url: "jdbc:postgresql://127.0.0.1:5432/test"
    driver-class: "org.postgresql.Driver"
  jpa:
    show-sql: true